import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link"
import ReduxProvider from "@/components/ReduxProvider";
import AuthInitializer  from "@/components/AuthInitializer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col items-center justify-center">
        <ReduxProvider>
          <AuthInitializer />
          <header className="w-full h-16 flex items-center justify-center bg-blue-300">
            <Link className="bg-blue-100 rounded-md border border-black p-3" href="/">Next Client Header</Link>
          </header>
          {children}
          <footer className="w-full h-16 flex items-center justify-center bg-gray-400">
            Next Client Footer
          </footer>
        </ReduxProvider>
      </body>
    </html>
  );
}
